language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kisenda/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kisenda/docker-react npm run test -- --coverage   